/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      phoneM: "375px",
      phoneL: "425px",
      tablet: "768px",
      laptop: "1024px",
      desktop: "1200px",
      bigscreen: "1440px",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
      8: "8px",
      10: "10px",
      title: "0.5em",
    },
    borderRadius: {
      4: "4px",
      6: "6px",
      none: "0",
      sm: "0.125rem",
      DEFAULT: "0.25rem",
      DEFAULT: "4px",
      md: "0.375rem",
      lg: "0.5rem",
      full: "9999px",
      large: "12px",
    },
    extend: {
      colors: {
        navbar1: "#3444cc",
        darknavbar1: "#1D2675",
        welcome1: "#191923",
        darkwelcome1: "#0D0D12",
        lockee1: "#BBBBBB",
        darklockee1: "#333333",
        projects1: "#2C8C99",
        darkprojects1: "#133D42",
        projects2: "#1B5860",
        contacts1: "#CBBFBB",
        darkcontacts1: "#4E413C",
        color5: "#431833",
        color6: "#BF1363",
        white: "#FDFDFD",
        darkwhite: "rgba(253, 253, 253, 0.9)",
        black: "#191923",
        topgradient: "#969696",
        btmgradient: "#000000",
        highlight: "#00bcd4",
        darkhighlight: "#00292E",
        terminalheader: "#3F3837",
        terminalbackground: "#1E1E1E",
        terminalcolor: "#FFFFFF",
        terminalcursor: "#929292",
        terminalborder: "#4B4B4B",
        terminalclose: "#FF6057",
        terminalminimize: "#FEBC2E",
        terminalmaximize: "#26C940",
      },
      animation: {
        mybounce: "bounce 0.5s ease infinite alternate",
      },
      keyframes: {
        mybounce: {
          "0%": { bottom: "40px" },
          "50%": { bottom: "60px" },
          "100%": { bottom: "40px" },
        },
      },
      typography: (theme) => ({
        project: {
          css: {
            h1: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            h2: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            h3: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            h4: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            h5: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            h6: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            p: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            ul: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            input: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            blockquote: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            li: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            table: {
              marginBottom: "0.5em !important",
              marginTop: "0.5em !important",
            },
            color: theme("colors.black"),
            "--tw-prose-body": theme("colors.black"),
            "--tw-prose-headings": theme("colors.black"),
            "--tw-prose-lead": theme("colors.black"),
            "--tw-prose-links": theme("colors.black"),
            "--tw-prose-bold": theme("colors.black"),
            "--tw-prose-counters": theme("colors.black"),
            "--tw-prose-bullets": theme("colors.black"),
            "--tw-prose-hr": theme("colors.black"),
            "--tw-prose-quotes": theme("colors.black"),
            "--tw-prose-quote-borders": theme("colors.black"),
            "--tw-prose-captions": theme("colors.black"),
            "--tw-prose-code": theme("colors.black"),
            "--tw-prose-pre-code": theme("colors.black"),
            "--tw-prose-pre-bg": theme("colors.black"),
            "--tw-prose-th-borders": theme("colors.black"),
            "--tw-prose-td-borders": theme("colors.black"),
          },
        },
      }),
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@rvxlab/tailwind-plugin-ios-full-height"),
  ],
};
