import Head from "next/head";
import { Navbar } from "@/components/navbar";
import { Welcome } from "@/components/welcome";
import { Projects } from "@/components/projects";
import { Contacts } from "@/components/contacts";
import { Footer } from "@/components/footer";
import { Lato } from "next/font/google";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NDev.fr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={lato.className}>
        <Navbar />
        <div
          className="absolute top-[84px] left-0 right-0 w-100 bottom-0 overflow-y-scroll snap-y snap-proximity"
          id="wrapper"
        >
          <Welcome />
          <Projects />
          <Contacts />
          <Footer />
        </div>
      </div>
    </>
  );
}
